# Generated by Django 3.0.7 on 2020-07-01 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MediCareApp', '0002_medicalimagefile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalRecordImage',
        ),
        migrations.AddField(
            model_name='medicalimagefile',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
