# Generated by Django 3.0.7 on 2020-07-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediCareApp', '0003_auto_20200701_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalimagefile',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicalimagefile',
            name='user',
            field=models.CharField(max_length=25),
        ),
    ]
