# Generated by Django 3.0.7 on 2020-07-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediCareApp', '0004_auto_20200701_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25)),
                ('phone', models.IntegerField(blank=True)),
                ('dob', models.DateField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('allergy', models.TextField(blank=True)),
                ('gender', models.CharField(blank=True, max_length=6)),
                ('blood_grp', models.CharField(blank=True, max_length=3)),
                ('height', models.IntegerField(blank=True)),
                ('weight', models.IntegerField(blank=True)),
            ],
        ),
    ]
