# Generated by Django 3.0.7 on 2020-07-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediCareApp', '0007_usermedicaldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalimagefile',
            name='extraction_status',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
