# Generated by Django 3.0.8 on 2020-07-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MediCareApp', '0006_auto_20200708_1036'),
        ('MediCareApp', '0008_medicalimagefile_extraction_status'),
    ]

    operations = [
    ]
