# Generated by Django 3.0.7 on 2020-07-19 16:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MediCareApp', '0008_medicalimagefile_extraction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalimagefile',
            name='category',
            field=models.CharField(default=datetime.datetime.now, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalimagefile',
            name='record_date',
            field=models.DateField(default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalimagefile',
            name='type',
            field=models.CharField(default=datetime.datetime.now, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalimagefile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
