# Generated by Django 3.0.8 on 2020-07-09 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MediCareApp', '0009_merge_20200709_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalimagefile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
