# Generated by Django 3.0.8 on 2020-07-19 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediCareApp', '0010_auto_20200709_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalimagefile',
            name='category',
            field=models.CharField(default=datetime.datetime.now, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalimagefile',
            name='record_date',
            field=models.DateField(default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalimagefile',
            name='type',
            field=models.CharField(default=datetime.datetime.now, max_length=25),
            preserve_default=False,
        ),
    ]
