# Generated by Django 3.0.8 on 2020-07-21 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MediCareApp', '0009_auto_20200719_2207'),
        ('MediCareApp', '0011_auto_20200719_2257'),
    ]

    operations = [
    ]
