# Generated by Django 2.1.5 on 2020-05-05 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_grp', models.CharField(choices=[('A+', 'A+ve'), ('A-', 'A-ve'), ('B+', 'B+ve'), ('B-', 'B-ve'), ('O+', 'O+ve'), ('O-', 'O-ve'), ('AB+', 'AB+ve'), ('AB-', 'AB-ve')], max_length=3)),
                ('height', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bpi', models.CharField(max_length=7)),
                ('cholestrol', models.CharField(max_length=3)),
                ('blood_sugar', models.PositiveIntegerField()),
                ('blood_count', models.PositiveIntegerField()),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=5)),
                ('phone', models.CharField(max_length=10)),
                ('relative_name', models.CharField(max_length=25)),
                ('relative_phone', models.CharField(max_length=10)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
