# Generated by Django 2.1.5 on 2020-05-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediLockerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='height',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='weight',
            field=models.PositiveIntegerField(),
        ),
    ]
